version: 2
jobs:
  build:
    working_directory: ~/nobrand-geospatial
    branches:
      only:
        - master
        - develop
        - /feature\/*/
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: install dependencies
          command: |
            virtualenv venv --python=python3.7
            source venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - '.venv'
            - '/usr/local/bin'
            - '/usr/local/lib/python3.7/site-packages'
      - run:
          name: run tests
          command: |
            source venv/bin/activate
            python -m unittest discover tests
